/**
 * Visual parameter definitions for all 33 Harry Potter Fantastic Beasts creatures.
 * Each entry drives the PixelCreature SVG renderer for egg, baby, and adult stages.
 */

export const CREATURE_DATA = {
  // ═══ N-Starter ═══
  niffler: {
    name: 'Niffler',
    colors: { primary: '#2C1810', secondary: '#4A3728', accent: '#D4A574', eye: '#1A1A1A' },
    bodyType: 'round',
    features: ['duck-bill', 'pouch', 'long-tail'],
    eggPattern: 'spots',
    eggColors: { base: '#8B7355', pattern: '#D4A574' },
  },
  bowtruckle: {
    name: 'Bowtruckle',
    colors: { primary: '#4A7C3F', secondary: '#6BA85A', accent: '#2D5A1E', eye: '#8BC34A' },
    bodyType: 'oval',
    features: ['twig-arms', 'leaf-crown'],
    eggPattern: 'runes',
    eggColors: { base: '#5D8A4E', pattern: '#A8D99C' },
  },
  demiguise: {
    name: 'Demiguise',
    colors: { primary: '#C0C0C0', secondary: '#E8E8E8', accent: '#8B8B8B', eye: '#4169E1' },
    bodyType: 'round',
    features: ['long-hair', 'big-eyes'],
    eggPattern: 'swirl',
    eggColors: { base: '#D3D3D3', pattern: '#F5F5F5' },
  },
  puffskein: {
    name: 'Puffskein',
    colors: { primary: '#DEB887', secondary: '#F5DEB3', accent: '#FFB6C1', eye: '#1A1A1A' },
    bodyType: 'round',
    features: ['fluffy', 'tongue'],
    eggPattern: 'spots',
    eggColors: { base: '#E8C99B', pattern: '#FFF0DB' },
  },

  // ═══ N-Gacha ═══
  mooncalf: {
    name: 'Mooncalf',
    colors: { primary: '#B8C6DB', secondary: '#D4E1F0', accent: '#7B9EC4', eye: '#4682B4' },
    bodyType: 'round',
    features: ['big-eyes', 'thin-legs'],
    eggPattern: 'swirl',
    eggColors: { base: '#C5D3E8', pattern: '#E8F0FF' },
  },
  fairy: {
    name: 'Fairy',
    colors: { primary: '#FFD700', secondary: '#FFF8DC', accent: '#FF69B4', eye: '#FF1493' },
    bodyType: 'round',
    features: ['wings', 'glow'],
    eggPattern: 'runes',
    eggColors: { base: '#FFF0B5', pattern: '#FFD700' },
  },
  firecrab: {
    name: 'Fire Crab',
    colors: { primary: '#CD5C5C', secondary: '#FF6347', accent: '#FFD700', eye: '#FFD700' },
    bodyType: 'insect',
    features: ['shell', 'gems', 'claws'],
    eggPattern: 'scales',
    eggColors: { base: '#D4736C', pattern: '#FFD700' },
  },
  diricawl: {
    name: 'Diricawl',
    colors: { primary: '#87CEEB', secondary: '#B0E0E6', accent: '#4682B4', eye: '#1A1A1A' },
    bodyType: 'bird',
    features: ['round-body', 'small-wings'],
    eggPattern: 'spots',
    eggColors: { base: '#ADD8E6', pattern: '#87CEEB' },
  },
  skrewt: {
    name: 'Skrewt',
    colors: { primary: '#696969', secondary: '#808080', accent: '#FF4500', eye: '#FF6347' },
    bodyType: 'insect',
    features: ['stinger', 'shell', 'fire-tail'],
    eggPattern: 'cracks',
    eggColors: { base: '#808080', pattern: '#FF4500' },
  },
  runespoor: {
    name: 'Runespoor',
    colors: { primary: '#8B4513', secondary: '#D2691E', accent: '#FF8C00', eye: '#FFD700' },
    bodyType: 'serpent',
    features: ['three-heads', 'scales'],
    eggPattern: 'scales',
    eggColors: { base: '#A0522D', pattern: '#FF8C00' },
  },

  // ═══ R ═══
  occamy: {
    name: 'Occamy',
    colors: { primary: '#4169E1', secondary: '#6495ED', accent: '#C0C0C0', eye: '#FFD700' },
    bodyType: 'serpent',
    features: ['wings', 'feathers', 'silver-scales'],
    eggPattern: 'scales',
    eggColors: { base: '#C0C0C0', pattern: '#4169E1' },
  },
  thunderbird: {
    name: 'Thunderbird',
    colors: { primary: '#DAA520', secondary: '#FFD700', accent: '#4169E1', eye: '#FFFFFF' },
    bodyType: 'bird',
    features: ['large-wings', 'lightning', 'crest'],
    eggPattern: 'cracks',
    eggColors: { base: '#C5A028', pattern: '#4169E1' },
  },
  hippogriff: {
    name: 'Hippogriff',
    colors: { primary: '#808080', secondary: '#A9A9A9', accent: '#FF8C00', eye: '#FF8C00' },
    bodyType: 'horse',
    features: ['wings', 'beak', 'talons'],
    eggPattern: 'stripes',
    eggColors: { base: '#A0A0A0', pattern: '#C0C0C0' },
  },
  kneazle: {
    name: 'Kneazle',
    colors: { primary: '#DEB887', secondary: '#F5DEB3', accent: '#8B4513', eye: '#228B22' },
    bodyType: 'feline',
    features: ['large-ears', 'long-tail', 'spots'],
    eggPattern: 'spots',
    eggColors: { base: '#E0C9A0', pattern: '#DEB887' },
  },
  swoopingevil: {
    name: 'Swooping Evil',
    colors: { primary: '#008B8B', secondary: '#00CED1', accent: '#9400D3', eye: '#00FF00' },
    bodyType: 'insect',
    features: ['butterfly-wings', 'cocoon'],
    eggPattern: 'swirl',
    eggColors: { base: '#006666', pattern: '#00CED1' },
  },
  zouwu: {
    name: 'Zouwu',
    colors: { primary: '#FF4500', secondary: '#FF8C00', accent: '#FFD700', eye: '#FFFFFF' },
    bodyType: 'feline',
    features: ['mane', 'long-tail', 'stripes'],
    eggPattern: 'stripes',
    eggColors: { base: '#CC3700', pattern: '#FFD700' },
  },
  grindylow: {
    name: 'Grindylow',
    colors: { primary: '#2E8B57', secondary: '#3CB371', accent: '#006400', eye: '#ADFF2F' },
    bodyType: 'round',
    features: ['tentacles', 'horns', 'webbed'],
    eggPattern: 'swirl',
    eggColors: { base: '#2E8B57', pattern: '#90EE90' },
  },
  boggart: {
    name: 'Boggart',
    colors: { primary: '#2F2F2F', secondary: '#4F4F4F', accent: '#8B0000', eye: '#FF0000' },
    bodyType: 'oval',
    features: ['shapeless', 'shadow', 'glow'],
    eggPattern: 'cracks',
    eggColors: { base: '#3A3A3A', pattern: '#8B0000' },
  },
  angorakneazle: {
    name: 'Angora Kneazle',
    colors: { primary: '#FFFAFA', secondary: '#FFF0F5', accent: '#FFB6C1', eye: '#4169E1' },
    bodyType: 'feline',
    features: ['fluffy', 'long-fur', 'hair-bow'],
    eggPattern: 'spots',
    eggColors: { base: '#FFF5EE', pattern: '#FFB6C1' },
  },
  fwooper: {
    name: 'Fwooper',
    colors: { primary: '#FF1493', secondary: '#FF69B4', accent: '#FFD700', eye: '#1A1A1A' },
    bodyType: 'bird',
    features: ['crest', 'long-tail-feathers', 'vibrant'],
    eggPattern: 'stripes',
    eggColors: { base: '#FF69B4', pattern: '#FFD700' },
  },

  // ═══ SR ═══
  unicorn: {
    name: 'Unicorn',
    colors: { primary: '#F8F8FF', secondary: '#E6E6FA', accent: '#C0C0C0', eye: '#4169E1' },
    bodyType: 'horse',
    features: ['horn', 'mane', 'glow'],
    eggPattern: 'swirl',
    eggColors: { base: '#F0F0FF', pattern: '#C0C0C0' },
  },
  nundu: {
    name: 'Nundu',
    colors: { primary: '#8B7355', secondary: '#CD853F', accent: '#556B2F', eye: '#ADFF2F' },
    bodyType: 'feline',
    features: ['mane', 'poison-breath', 'large'],
    eggPattern: 'spots',
    eggColors: { base: '#9C8565', pattern: '#556B2F' },
  },
  graphorn: {
    name: 'Graphorn',
    colors: { primary: '#696969', secondary: '#808080', accent: '#DAA520', eye: '#DAA520' },
    bodyType: 'round',
    features: ['horns', 'thick-hide', 'tentacle-mouth'],
    eggPattern: 'cracks',
    eggColors: { base: '#808080', pattern: '#DAA520' },
  },
  abraxan: {
    name: 'Abraxan',
    colors: { primary: '#DAA520', secondary: '#FFD700', accent: '#FFFFFF', eye: '#8B4513' },
    bodyType: 'horse',
    features: ['large-wings', 'mane', 'massive'],
    eggPattern: 'swirl',
    eggColors: { base: '#C5A028', pattern: '#FFD700' },
  },
  redcap: {
    name: 'Red Cap',
    colors: { primary: '#556B2F', secondary: '#6B8E23', accent: '#8B0000', eye: '#FF0000' },
    bodyType: 'humanoid',
    features: ['red-hat', 'club', 'small'],
    eggPattern: 'cracks',
    eggColors: { base: '#556B2F', pattern: '#8B0000' },
  },
  centaur: {
    name: 'Centaur',
    colors: { primary: '#8B7355', secondary: '#D2B48C', accent: '#1C1C1C', eye: '#2F4F4F' },
    bodyType: 'humanoid',
    features: ['horse-body', 'bow', 'stars'],
    eggPattern: 'runes',
    eggColors: { base: '#A08060', pattern: '#1C1C1C' },
  },
  jarvey: {
    name: 'Jarvey',
    colors: { primary: '#D2B48C', secondary: '#F5DEB3', accent: '#8B4513', eye: '#1A1A1A' },
    bodyType: 'oval',
    features: ['long-body', 'sharp-teeth', 'ferret'],
    eggPattern: 'stripes',
    eggColors: { base: '#C4A87A', pattern: '#8B4513' },
  },
  augurey: {
    name: 'Augurey',
    colors: { primary: '#2F4F4F', secondary: '#4F6F6F', accent: '#4682B4', eye: '#7FFFD4' },
    bodyType: 'bird',
    features: ['ragged-feathers', 'long-beak', 'mournful'],
    eggPattern: 'swirl',
    eggColors: { base: '#3A5A5A', pattern: '#4682B4' },
  },

  // ═══ SSR ═══
  phoenix: {
    name: 'Phoenix',
    colors: { primary: '#FF4500', secondary: '#FFD700', accent: '#FF0000', eye: '#FFFFFF' },
    bodyType: 'bird',
    features: ['flame-wings', 'long-tail-feathers', 'glow', 'fire-trail'],
    eggPattern: 'cracks',
    eggColors: { base: '#FF6347', pattern: '#FFD700' },
  },
  basilisk: {
    name: 'Basilisk',
    colors: { primary: '#006400', secondary: '#228B22', accent: '#FFD700', eye: '#FFD700' },
    bodyType: 'serpent',
    features: ['crest', 'fangs', 'large', 'deadly-eyes'],
    eggPattern: 'scales',
    eggColors: { base: '#2E5A1E', pattern: '#FFD700' },
  },
  qilin: {
    name: 'Qilin',
    colors: { primary: '#DAA520', secondary: '#F0E68C', accent: '#FFFFFF', eye: '#87CEEB' },
    bodyType: 'horse',
    features: ['scales', 'antlers', 'glow', 'gentle'],
    eggPattern: 'runes',
    eggColors: { base: '#C5A028', pattern: '#F0E68C' },
  },
  horntail: {
    name: 'Hungarian Horntail',
    colors: { primary: '#1C1C1C', secondary: '#363636', accent: '#FF4500', eye: '#FF4500' },
    bodyType: 'bird',
    features: ['large-wings', 'horns', 'spikes', 'fire-breath', 'tail-spikes'],
    eggPattern: 'cracks',
    eggColors: { base: '#2D2D2D', pattern: '#FF4500' },
  },
  thestral: {
    name: 'Thestral',
    colors: { primary: '#1C1C1C', secondary: '#2D2D2D', accent: '#696969', eye: '#E0E0E0' },
    bodyType: 'horse',
    features: ['bat-wings', 'skeletal', 'mane', 'ghostly'],
    eggPattern: 'swirl',
    eggColors: { base: '#252525', pattern: '#696969' },
  },
};

/** SSR creature IDs that get the special glow treatment */
export const SSR_CREATURES = new Set([
  'phoenix',
  'basilisk',
  'qilin',
  'horntail',
  'thestral',
]);
